### ISSUE TITLE
Too few arguments to function App\Ldap\LdapAuthenticator::__construct()

### ISSUE THREAD

**Issue by drustan** [kimai/kimai#4478]
### Describe the issue

Hi!

I would like to express my gratitude first for all the work you've done developing Kimai.

The bug showed up, when I upgraded from 2.4.0 to 2.5.0. I used to authenticate via LDAP some time ago, but I switched to SSO 4 months ago and everything worked like a charm until now.

I actually don't understand why I get this message since I have disabled LDAP auth :

```
kimai:
    ldap:
        activate: false
    saml:
        provider: keycloak
        activate: true
        title: Keycloak
[…]
```

Is there anything I'm missing here?

Thanks for your help.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.5.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

[2023-12-04T13:52:22.413216+00:00] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\Security\\SecurityController::loginAction","_locale":"en"},"request_uri":"http://localhost/en/login","method":"GET"} {"channel":"request"}
[2023-12-04T13:52:22.425203+00:00] php.CRITICAL: Uncaught Error: Too few arguments to function App\Ldap\LdapAuthenticator::__construct(), 2 passed in /opt/kimai/var/cache/prod/ContainerVUU63bs/getSecurity_Authenticator_KimaiLdap_SecuredAreaService.php on line 31 and exactly 3 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Ldap\\LdapAuthenticator::__construct(), 2 passed in /opt/kimai/var/cache/prod/ContainerVUU63bs/getSecurity_Authenticator_KimaiLdap_SecuredAreaService.php on line 31 and exactly 3 expected at /opt/kimai/src/Ldap/LdapAuthenticator.php:26)"} {"channel":"php"}
[2023-12-04T13:52:22.425998+00:00] request.CRITICAL: Uncaught PHP Exception ArgumentCountError: "Too few arguments to function App\Ldap\LdapAuthenticator::__construct(), 2 passed in /opt/kimai/var/cache/prod/ContainerVUU63bs/getSecurity_Authenticator_KimaiLdap_SecuredAreaService.php on line 31 and exactly 3 expected" at /opt/kimai/src/Ldap/LdapAuthenticator.php line 26 {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function App\\Ldap\\LdapAuthenticator::__construct(), 2 passed in /opt/kimai/var/cache/prod/ContainerVUU63bs/getSecurity_Authenticator_KimaiLdap_SecuredAreaService.php on line 31 and exactly 3 expected at /opt/kimai/src/Ldap/LdapAuthenticator.php:26)"} {"channel":"request"}
localhost:8001 10.42.1.13 - - [04/Dec/2023:14:52:22 +0100] "GET /en/login HTTP/1.1" 500 1917 "-" "kube-probe/1.28"

**Comment by kevinpapst** [comment]
@tobybatch we really need to delete the entire cache after an update. I have had reports about similar bugs from docker users too often now. Maybe we can even delete the entire `/opt/kimai/var/cache/prod/` folder always on every start? 
will have a neglectable performance impact of a couple of seconds the most. but has the benefit of always using the latest sources.

@drustan you are using an old cache with a new kimai version. we have to figure out a way to fix that in the docker container. until then you can remove the directory or simply force a cache reload.

**Comment by drustan** [comment]
@kevinpapst Yes, you're right indeed, that was that. Sorry for the bother. Thanks

**Comment by Borega** [comment]
got the same error. When trying to reload cache i get:
In DefinitionErrorExceptionPass.php line 49:
 [ERROR] Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$loginLink" of method "__construct()"    
         references interface "Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface" but no such service 
         exists. Did you create a class that implements this interface?     

same when reloading manually

**Comment by kevinpapst** [comment]
Do NOT mount the entire var/ directory including the cache folder or even worse, the entire config directory.
You are asking for troubles.

**Comment by PentaPaetzold** [comment]
can you please explain what to do else then mounting var?
i have volume
kimai_var:/opt/kimai/var
as it was written in the docs.

already cleared the cache with
`rm -r /var/cache/*`
in the container as advised.

still it does not work on kimai 2.4.0:

```
885bbe071f69:/var/www/html# /opt/kimai/bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false                                                        


In DefinitionErrorExceptionPass.php line 49:
                                                                                                                                                                              
  Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$loginLink" of method "__construct()" references interface "Symfony\Component\Security\Http\LoginLin  
  k\LoginLinkHandlerInterface" but no such service exists. Did you create a class that implements this interface?                                                             
                                                                                                                                                                              

cache:clear [--no-warmup] [--no-optional-warmers]

885bbe071f69:/var/www/html# /opt/kimai/bin/console cache:warmup --env=prod

 // Warming up the cache for the prod environment with debug false                                                      

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.                                           
                                                                                                                        

885bbe071f69:/var/www/html# /opt/kimai/bin/console kimai:reload --env=prod
 Validating config file syntax ...

                                                                                                                        
 [OK] All 26 YAML files contain valid syntax.                                                                           
                                                                                                                        
 [OK] All 629 XLIFF files contain valid syntax.                                                                         

 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false                                                        
                                                                                                                        
 [ERROR] Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$loginLink" of method "__construct()"    
         references interface "Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface" but no such service 
         exists. Did you create a class that implements this interface?                                                 
                                                                                                                        
 [WARNING] Cache could not be rebuilt.                                                                                  
                                                                                                                        
           Please run these commands to rebuild the cache manually:                                                     
                                                                                                                        
           rm -r var/cache/*                                                                                            
           bin/console cache:clear --env=prod                                                                           
           bin/console cache:warmup --env=prod

```
what to do?

**Comment by kevinpapst** [comment]
Stop posting in closed issues.
Stop commenting on issues that are NOT related to your error message.
Stop posting with missing information (like the used composer files).
Open new issues instead.
